% vraci strukturu df2sos
function Hd = My_IIR_PP_Hd(Fstop1, Fpass1, Fpass2, Fstop2)
%GETFILTER Returns a discrete-time filter System object.

% MATLAB Code
% Generated by MATLAB(R) 24.2 and DSP System Toolbox 24.2.
% Generated on: 18-Nov-2024 16:45:55

% Fstop1 = 2200;   % First Stopband Frequency
% Fpass1 = 3600;   % First Passband Frequency
% Fpass2 = 5000;   % Second Passband Frequency
% Fstop2 = 5800;   % Second Stopband Frequency
Astop1 = 80;     % First Stopband Attenuation (dB)
Apass  = 0.1;    % Passband Ripple (dB)
Astop2 = 80;     % Second Stopband Attenuation (dB)
Fs     = 48000;  % Sampling Frequency

% h = fdesign.bandpass('fst1,fp1,fp2,fst2,ast1,ap,ast2', Fstop1, Fpass1, ...
%     Fpass2, Fstop2, Astop1, Apass, Astop2, Fs);
% 
% Hd = design(h, 'ellip', ...
%     'MatchExactly', 'both', ...
%     'SystemObject', true);

match  = 'both';  % Band to match exactly

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2, Fs);
Hd = design(h, 'ellip', 'MatchExactly', match);


end